export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

HISTFILE=~/.history
HISTSIZE=10000
SAVEHIST=50000

setopt inc_append_history

# begone annoying ~ in terminal paste
unset zle_bracketed_paste

if [[ "$(uname)" == "Linux" ]]; then
  if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
  else
    setxkbmap -option caps:escape
  fi
fi