(require 'hummingbird-avy)
(require 'hummingbird-anzu)
(require 'hummingbird-evil)
(require 'hummingbird-fci)
(require 'hummingbird-flycheck)
(require 'hummingbird-projectile)
(require 'hummingbird-helm)
(require 'hummingbird-js2mode)
(require 'hummingbird-markdown)
(require 'hummingbird-magit)
(require 'hummingbird-webmode)
(require 'hummingbird-spaceline)
(require 'hummingbird-autocomplete)

(provide 'hummingbird-modules)
