general {
    lock_cmd = pidof hyprlock                              # disable lock
    before_sleep_cmd = true                                # disable lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on             # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 0                                      # don't wait for lock
}

# All lock/screensaver listeners disabled
