# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 6

    # Use master layout instead of dwindle (better for ultrawide)
    # layout = master
    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 4
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens (if using dwindle)
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    # Prevent single windows from being stupidly wide on ultrawide
    orientation = center
    mfact = 0.60  # master window takes 60% of screen width
}
